# Generated by Django 3.1.5 on 2021-01-18 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('source', models.CharField(max_length=25)),
                ('headline', models.TextField(primary_key=True, serialize=False)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('fetched_on', models.DateTimeField(auto_now=True)),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'headlines',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('frequency', models.FloatField()),
                ('articles', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('data', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
    ]
