# Generated by Django 2.2.6 on 2019-10-26 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=25)),
                ('headline', models.TextField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('fetched_on', models.DateTimeField()),
                ('link', models.TextField()),
            ],
        ),
    ]
